### PR TITLE
All API calls are now under the new domain carto.com

### PR DESCRIPTION
**Pull request by nachoorme**
With these changes all API calls will be requested to the new domain carto.com

### CODE REVIEW

**Comment by jsanz** [comment]
LGTM, @ethervoid can you take a quick look so we can merge this?

**Comment by jsanz** [comment]
Hi @nachoorme sorry for the delay, to accept the pull request we need you first to send us a signed CLA, more details [here](https://carto.com/contributing). Would you mind doing this, please?

**Comment by nachoorme** [comment]
@jsanz I signed the CLA last week. Do you need anything else from my side?

**Comment by agnesgyorfi** [comment]
Good morning, @jsanz!  We have @nachoorme's signed CLA, so we're good to go.  Nacho, thanks again for getting that back to us so quickly, and for your contributions! Happy new year 😄

**Comment by jsanz** [comment]
Great, thanks @agnesgyorfi (sorry for the delay, I was on holidays)

@ethervoid do you mind taking a look at the changes?

**Comment by ethervoid** [comment]
Looks good to me

**Pull request merged**
